### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by johntilley** [chad3814/node-native-set#3]
Would be useful if can read in array as per specification

var mySet = new Set([1,2,3])

**Comment by chad3814** [comment]
yeah I've been meaning to add that, I'll get that done at work tomorrow

**Comment by johntilley** [comment]
Thank you. Nice job so far. Its frigging fast.

**Comment by johntilley** [comment]
Thank you. Nice job so far. Its frigging fast.

**Comment by chad3814** [comment]
Okay, so, a little later than I wanted, but there ya go, 0.3.3 was published to npm and you can specify an array in the constructor.

**Comment by johntilley** [comment]
Thank you
