### ISSUE TITLE
Leaks memory on MACOSX and Ubuntu 14.10

### ISSUE THREAD

**Issue by lisa-lionheart** [chad3814/node-native-set#4]
If you run this code with the --expose-gc flag, the memory of the usage will go up and up and up until it falls over

var Set = require('es6-native-set');

function cycle() {

    console.log(Date.now());

    var test = new Set();

    for(var i=0; i < 10000; i++) {
        test.add(Date.now().toString());
    }

    test = null;

    global.gc();

    setTimeout(cycle, 0);
}

cycle();

**Comment by chad3814** [comment]
I know there is a memory leak, we see it at my job too. The above code makes it look like the destructor isn't working right, I'll look into it today, thanks.

**Comment by chad3814** [comment]
@lisa-lionheart npm published version 1.0.0 no longer has (at least the trivially displayed memory leak)

**Comment by lisa-lionheart** [comment]
Nice one, I can confirm this has fixed all the issues I was seeing
