### ISSUE TITLE
Segfault on undefined

### ISSUE THREAD

**Issue by lordnynex** [chad3814/node-native-set#6]
I was writing some unit tests and trying to generate the TypeError exception in NodeSet::Add on arg length < 1.

```javascript
set.add(undefined);
```

Not sure this is a real world scenario but it'd be nice to patch this up against segfaults.

**Comment by chad3814** [comment]
that will actually give a length of 1, so yeah I'll make a fix that undefined is not a valid key

**Comment by lordnynex** [comment]
:+1: Unit tests passing :)
